import { AppShell } from "@/components/AppShell";
import { PageHeader } from "@/components/ui/PageHeader";
import { apiGet } from "@/lib/server-api";
import { requireUser } from "@/lib/auth";
import { BackupsTable, type BackupRow } from "./BackupsTable";

export default async function BackupsPage() {
  await requireUser();
  const data = await apiGet<{ backups: BackupRow[] }>("/api/backups").catch(() => ({ backups: [] }));

  return (
    <AppShell>
      <PageHeader eyebrow="Recovery" title="Backup catalog" description="Local backup records generated by the worker." />
      <BackupsTable backups={data.backups} />
    </AppShell>
  );
}
